Tech 7097 add prometheus configuration
Invoca/invoca-metrics pull request #65
Opened 2022-02-10 21:35 UTC by jebentier

This PR is adding the ability to configure prometheus metric exposure. With these changes you can either start a webserver in a separate thread to export metrics directly, or configure a remote host to push metrics to. In order to get these changes out into web we'll be releasing under `v1.9.0` and avoiding the major version bump until we remove the graphite support. This is so that we don't have to do an unnecessary major version bump to get time to value quickly.

2022-02-10 23:45 UTC, dcaddell requested changes
Looks great and I really like the frozen config pattern! Just a couple questions/suggestions from me.

2022-02-10 23:45 UTC, dcaddell commented on lib/invoca/metrics/prometheus/configuration.rb
> +        #   - `:direct` (default):  Exports metrics directly using a threaded webserver.
I don't see us setting this default anywhere? Should we be defaulting to `:direct` or does this comment just need updating?

2022-02-10 23:45 UTC, dcaddell commented on lib/invoca/metrics/prometheus/configuration.rb
> +          @client = PrometheusExporter::Client.new(host: host, port: port)
If host/port aren't configured the `PrometheusExporter::Client` will default to `host: 'localhost'` and `port: 9394`. I think those are nice, sane defaults but we should document the behavior on our end.

We could also validate that these values are configured when in `:push` mode? (ditto for `port` when in `:direct` mode)

2022-02-10 23:45 UTC, dcaddell commented on lib/invoca/metrics/prometheus.rb
> +      class << self
What would you think about adding something like `delegate :client, to :config` as just a little QoL improvement for users? Seems like they'd be interacting with the client 99% of the time.

2022-02-11 14:07 UTC, jebentier commented on lib/invoca/metrics/prometheus/configuration.rb
> +        #   - `:direct` (default):  Exports metrics directly using a threaded webserver.
Ha! AI autocomplete getting ahead of itself with documentation for me. This is a good catch. I was thinking we want to make `mode` have to be explicit (remove the default), but I would like to open that question up to the team whether or not we feel it's necessary to have a default mode, and what is the safer option for it to be?

2022-02-11 14:16 UTC, jebentier commented on lib/invoca/metrics/prometheus.rb
> +      class << self
Great idea, though I think what is being interacted with will depend on the mode, so I think what we'll want is a separate `collector` or something object that is exposed from the `Configuration` object. And with taking Colin's suggestion in mind I would rather not expose that directly out of the global, and rather only out of the `Configuration` to force downstream object to have to pass the configuration object around rather than referencing the global all the time.

2022-02-11 14:22 UTC, jebentier commented on lib/invoca/metrics/prometheus/configuration.rb
> +          @client = PrometheusExporter::Client.new(host: host, port: port)
Good call, I've added the defaults and validations e0d110a5dd0c36c278782b98553ba6b32c6420c0

2022-02-11 16:26 UTC, dcaddell commented on lib/invoca/metrics/prometheus/configuration.rb
> +        #   - `:direct` (default):  Exports metrics directly using a threaded webserver.
I like requiring users to configure a `mode` personally.

2022-02-11 17:07 UTC, jebentier commented on lib/invoca/metrics/prometheus/configuration.rb
> +          @client = PrometheusExporter::Client.new(host: host, port: port)
It's kind of an extra safety to protect against passing in `host = nil`. This could happen in the case where the upstream code is using service discovery or some other method of setting the host and it returns `nil`.

2022-02-11 17:10 UTC, dcaddell approved these changes

2022-02-12 04:45 UTC, ColinDKelley approved these changes

2022-02-14 19:17 UTC, gwynethallwright approved these changes

2022-02-14 19:19 UTC, gwynethallwright commented on lib/invoca/metrics/prometheus/configuration.rb
> +        #   - `:direct` (default):  Exports metrics directly using a threaded webserver.
Not familiar enough with the metrics code to have a strong opinion, but I also like the idea of requiring users to configure a mode.

2022-02-16 17:04 UTC, yinonrousso approved these changes

2022-02-22 14:49 UTC, merged